# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'credit.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(651, 376)
        MainWindow.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.422343 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.text_fio = QLineEdit(self.centralwidget)
        self.text_fio.setObjectName(u"text_fio")
        self.text_fio.setGeometry(QRect(10, 40, 331, 22))
        self.text_fio.setStyleSheet(u"border-radius:4px;")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 49, 16))
        font = QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.text_Issued = QLineEdit(self.centralwidget)
        self.text_Issued.setObjectName(u"text_Issued")
        self.text_Issued.setGeometry(QRect(180, 100, 241, 22))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 100, 81, 21))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.text_seria_1 = QLineEdit(self.centralwidget)
        self.text_seria_1.setObjectName(u"text_seria_1")
        self.text_seria_1.setGeometry(QRect(70, 70, 31, 22))
        self.text_seria_1.setStyleSheet(u"border-radius:4px;")
        self.text_seria_1.setMaxLength(1)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 70, 49, 21))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.text_seria_2 = QLineEdit(self.centralwidget)
        self.text_seria_2.setObjectName(u"text_seria_2")
        self.text_seria_2.setGeometry(QRect(110, 70, 31, 22))
        self.text_seria_2.setStyleSheet(u"border-radius:4px;")
        self.text_seria_2.setMaxLength(1)
        self.text_seria_3 = QLineEdit(self.centralwidget)
        self.text_seria_3.setObjectName(u"text_seria_3")
        self.text_seria_3.setGeometry(QRect(150, 70, 31, 22))
        self.text_seria_3.setStyleSheet(u"border-radius:4px;")
        self.text_seria_3.setMaxLength(1)
        self.text_seria_4 = QLineEdit(self.centralwidget)
        self.text_seria_4.setObjectName(u"text_seria_4")
        self.text_seria_4.setGeometry(QRect(190, 70, 31, 22))
        self.text_seria_4.setStyleSheet(u"border-radius:4px;")
        self.text_seria_4.setMaxLength(1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(230, 70, 21, 21))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.text_number_4 = QLineEdit(self.centralwidget)
        self.text_number_4.setObjectName(u"text_number_4")
        self.text_number_4.setGeometry(QRect(380, 70, 31, 22))
        self.text_number_4.setStyleSheet(u"border-radius:4px;")
        self.text_number_4.setMaxLength(1)
        self.text_number_3 = QLineEdit(self.centralwidget)
        self.text_number_3.setObjectName(u"text_number_3")
        self.text_number_3.setGeometry(QRect(340, 70, 31, 22))
        self.text_number_3.setStyleSheet(u"border-radius:4px;")
        self.text_number_3.setMaxLength(1)
        self.text_number_2 = QLineEdit(self.centralwidget)
        self.text_number_2.setObjectName(u"text_number_2")
        self.text_number_2.setGeometry(QRect(300, 70, 31, 22))
        self.text_number_2.setStyleSheet(u"border-radius:4px;")
        self.text_number_2.setMaxLength(1)
        self.text_number_1 = QLineEdit(self.centralwidget)
        self.text_number_1.setObjectName(u"text_number_1")
        self.text_number_1.setGeometry(QRect(260, 70, 31, 22))
        self.text_number_1.setStyleSheet(u"border-radius:4px;")
        self.text_number_1.setMaxLength(1)
        self.text_date_4 = QLineEdit(self.centralwidget)
        self.text_date_4.setObjectName(u"text_date_4")
        self.text_date_4.setGeometry(QRect(310, 130, 31, 22))
        self.text_date_4.setStyleSheet(u"border-radius:4px;")
        self.text_date_4.setMaxLength(1)
        self.text_date_3 = QLineEdit(self.centralwidget)
        self.text_date_3.setObjectName(u"text_date_3")
        self.text_date_3.setGeometry(QRect(270, 130, 31, 22))
        self.text_date_3.setStyleSheet(u"border-radius:4px;")
        self.text_date_3.setMaxLength(1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 130, 91, 21))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.text_date_5 = QLineEdit(self.centralwidget)
        self.text_date_5.setObjectName(u"text_date_5")
        self.text_date_5.setGeometry(QRect(360, 130, 31, 22))
        self.text_date_5.setStyleSheet(u"border-radius:4px;")
        self.text_date_5.setMaxLength(1)
        self.text_date_8 = QLineEdit(self.centralwidget)
        self.text_date_8.setObjectName(u"text_date_8")
        self.text_date_8.setGeometry(QRect(480, 130, 31, 22))
        self.text_date_8.setStyleSheet(u"border-radius:4px;")
        self.text_date_8.setMaxLength(1)
        self.text_date_7 = QLineEdit(self.centralwidget)
        self.text_date_7.setObjectName(u"text_date_7")
        self.text_date_7.setGeometry(QRect(440, 130, 31, 22))
        self.text_date_7.setStyleSheet(u"border-radius:4px;")
        self.text_date_7.setMaxLength(1)
        self.text_date_2 = QLineEdit(self.centralwidget)
        self.text_date_2.setObjectName(u"text_date_2")
        self.text_date_2.setGeometry(QRect(220, 130, 31, 22))
        self.text_date_2.setStyleSheet(u"border-radius:4px;")
        self.text_date_2.setMaxLength(1)
        self.text_date_6 = QLineEdit(self.centralwidget)
        self.text_date_6.setObjectName(u"text_date_6")
        self.text_date_6.setGeometry(QRect(400, 130, 31, 22))
        self.text_date_6.setStyleSheet(u"border-radius:4px;")
        self.text_date_6.setMaxLength(1)
        self.text_date_1 = QLineEdit(self.centralwidget)
        self.text_date_1.setObjectName(u"text_date_1")
        self.text_date_1.setGeometry(QRect(180, 130, 31, 22))
        self.text_date_1.setStyleSheet(u"border-radius:4px;")
        self.text_date_1.setMaxLength(1)
        self.text_code = QLineEdit(self.centralwidget)
        self.text_code.setObjectName(u"text_code")
        self.text_code.setGeometry(QRect(180, 160, 241, 22))
        self.text_code.setStyleSheet(u"border-radius:4px;")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 160, 151, 21))
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 190, 131, 16))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.text_family = QComboBox(self.centralwidget)
        self.text_family.addItem("")
        self.text_family.addItem("")
        self.text_family.addItem("")
        self.text_family.addItem("")
        self.text_family.setObjectName(u"text_family")
        self.text_family.setEnabled(True)
        self.text_family.setGeometry(QRect(180, 190, 241, 22))
        self.text_family.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.text_family.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_family.setStyleSheet(u"border-radius:4px;")
        self.text_family.setEditable(False)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 220, 111, 21))
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.text_address = QLineEdit(self.centralwidget)
        self.text_address.setObjectName(u"text_address")
        self.text_address.setGeometry(QRect(180, 220, 241, 22))
        self.text_address.setStyleSheet(u"border-radius:4px;")
        self.text_address_pr = QLineEdit(self.centralwidget)
        self.text_address_pr.setObjectName(u"text_address_pr")
        self.text_address_pr.setGeometry(QRect(180, 250, 241, 22))
        self.text_address_pr.setStyleSheet(u"border-radius:4px;")
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 250, 121, 21))
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 280, 71, 16))
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.text_number = QLineEdit(self.centralwidget)
        self.text_number.setObjectName(u"text_number")
        self.text_number.setGeometry(QRect(180, 280, 241, 22))
        self.text_number.setStyleSheet(u"border-radius:4px;")
        self.text_number.setMaxLength(10)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(150, 280, 21, 16))
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 310, 49, 16))
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.text_email = QLineEdit(self.centralwidget)
        self.text_email.setObjectName(u"text_email")
        self.text_email.setGeometry(QRect(180, 310, 241, 22))
        self.text_email.setStyleSheet(u"border-radius:4px;")
        self.text_connection = QComboBox(self.centralwidget)
        self.text_connection.addItem("")
        self.text_connection.addItem("")
        self.text_connection.addItem("")
        self.text_connection.setObjectName(u"text_connection")
        self.text_connection.setEnabled(True)
        self.text_connection.setGeometry(QRect(180, 340, 241, 22))
        self.text_connection.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.text_connection.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_connection.setStyleSheet(u"border-radius:4px;\n"
"")
        self.text_connection.setEditable(False)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 340, 81, 16))
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(u"background-color:rgba(0,0,0,0)")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(540, 340, 101, 24))
        self.pushButton.setStyleSheet(u"QPushButton {\n"
"    border-radius:4px;\n"
"	font-size:17px;\n"
"}\n"
"QPushButton:hover {\n"
"font-size:15px;\n"
"border-radius:4px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.422343 rgba(155, 79, 165, 255), stop:1 rgba( 41, 61, 132, 235));\n"
"    color: white; \n"
"}")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u0424\u0418\u041e", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0435\u043c \u0432\u044b\u0434\u0430\u043d", None))
        self.text_seria_1.setPlaceholderText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0435\u0440\u0438\u044f", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u2116", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0430\u0442\u0430 \u0432\u044b\u0434\u0430\u0447\u0438", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u0434 \u043f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u0438\u044f", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0435\u043c\u0435\u0439\u043d\u043e\u0435 \u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435", None))
        self.text_family.setItemText(0, QCoreApplication.translate("MainWindow", u"\u0425\u043e\u043b\u043e\u0441\u0442/\u043d\u0435 \u0437\u0430\u043c\u0443\u0436\u0435\u043c", None))
        self.text_family.setItemText(1, QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u0432\u0435\u0434\u0435\u043d/\u0420\u0430\u0437\u0432\u0435\u0434\u0435\u043d\u0430", None))
        self.text_family.setItemText(2, QCoreApplication.translate("MainWindow", u"\u0416\u0435\u043d\u0430\u0442/\u0417\u0430\u043c\u0443\u0436\u0435\u043c", None))
        self.text_family.setItemText(3, QCoreApplication.translate("MainWindow", u"\u0412\u0434\u043e\u0432\u0435\u043d/\u0412\u0434\u043e\u0432\u0430", None))

        self.text_family.setCurrentText(QCoreApplication.translate("MainWindow", u"\u0425\u043e\u043b\u043e\u0441\u0442/\u043d\u0435 \u0437\u0430\u043c\u0443\u0436\u0435\u043c", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u0410\u0434\u0440\u0435\u0441 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u0410\u0434\u0440\u0435\u0441 \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u044f", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0435\u043b\u0435\u0444\u043e\u043d", None))
        self.text_number.setText("")
        self.text_number.setPlaceholderText(QCoreApplication.translate("MainWindow", u"(___)-__-__", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"+7", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.text_connection.setItemText(0, QCoreApplication.translate("MainWindow", u"Telegram", None))
        self.text_connection.setItemText(1, QCoreApplication.translate("MainWindow", u"\u0422\u0435\u043b\u0435\u0444\u043e\u043d", None))
        self.text_connection.setItemText(2, QCoreApplication.translate("MainWindow", u"Email", None))

        self.text_connection.setCurrentText(QCoreApplication.translate("MainWindow", u"Telegram", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0438\u0434 \u0441\u0432\u044f\u0437\u0438", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c", None))
    # retranslateUi

